apiVersion: v1
kind: Service
metadata:
  name: argocd-git-override
  namespace: openshift-gitops
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: argocd-git-override
  labels:
    app: argocd-git-override
spec:
  ports:
    - name: https
      port: 443
      targetPort: https
  selector:
    app: argocd-git-override