apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-git-override
data:
  map.yaml: |-
    map:
    - upstreamRepoURL: https://github.com/csantanapr/argocd-git-override.git
      originRepoUrL: https://github.com/fork/argocd-git-override.git
      originBranch: fork-branch

