apiVersion: v1
kind: Service
metadata:
  name: argocd-git-override
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: argocd-git-override
  labels:
    app: argocd-git-override
spec:
  ports:
    - name: https
      port: 443
      targetPort: https
  selector:
    app: argocd-git-override
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-git-override
  annotations:
    app.openshift.io/vcs-ref: main
    app.openshift.io/vcs-uri: https://github.com/csantanapr/argocd-git-override
  labels:
    app: argocd-git-override
    version: v1
    app.kubernetes.io/component: argocd-git-override
    app.kubernetes.io/instance: argocd-git-override
    app.kubernetes.io/name: argocd-git-override
    app.kubernetes.io/part-of: argocd-git-override
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: "14"
spec:
  selector:
    matchLabels:
      app: argocd-git-override
      version: v1
  template:
    metadata:
      labels:
        app: argocd-git-override
        version: v1
    spec:
      volumes:
      - name: certs
        secret:
          secretName: argocd-git-override
      - name: config
        configMap:
          name: argocd-git-override
          items:
          - key: "map.yaml"
            path: "map.yaml"
      containers:
        - name: argocd-git-override
          image: argocd-git-override
          ports:
            - containerPort: 8443
              name: https
          envFrom:
            - secretRef:
                name: argocd-git-override
          volumeMounts:
          - name: certs
            mountPath: "/certs"
            readOnly: true
          - name: config
            mountPath: "/config"
            readOnly: true
          resources:
            requests:
              memory: "100Mi"
              cpu: "5m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          livenessProbe:
            tcpSocket:
              port: 8443
          readinessProbe:
            tcpSocket:
              port: 8443